// ============================================================
// 🌱 SEED DATA — 50 Products (matches productModel.js schema)
// ============================================================
// Seller IDs below are placeholders.
// Replace with real ObjectIds from your User collection,
// or run the seeder with --create-seller flag (see seedDB.js).
// ============================================================

const { Types } = require("mongoose");

// Placeholder seller IDs — replace with real ones from your DB
const sellers = [
  new Types.ObjectId("665f1a2b3c4d5e6f7a8b9c01"),
  new Types.ObjectId("665f1a2b3c4d5e6f7a8b9c02"),
  new Types.ObjectId("665f1a2b3c4d5e6f7a8b9c03"),
];

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

const products = [
  // ─── ELECTRONICS (15) ────────────────────────────────────
  {
    name: "Sony WH-1000XM5 Wireless Headphones",
    description:
      "Industry-leading noise cancelling headphones with Auto NC Optimizer, crystal clear hands-free calling, and up to 30-hour battery life.",
    price: 349.99,
    discountPrice: 279.99,
    category: "electronics",
    stock: 85,
    images: ["wh1000xm5_1.jpg", "wh1000xm5_2.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Apple iPad Air 11-inch (M2)",
    description:
      "Supercharged by the M2 chip, the iPad Air features a stunning Liquid Retina display, USB-C connectivity, and all-day battery life.",
    price: 599.99,
    discountPrice: 549.99,
    category: "electronics",
    stock: 60,
    images: ["ipad_air_m2_1.jpg", "ipad_air_m2_2.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Samsung 65-inch QLED 4K Smart TV",
    description:
      "Quantum Dot technology delivers 100% color volume with vivid, lifelike colors. Quantum HDR 12x and Object Tracking Sound for immersive viewing.",
    price: 1199.99,
    discountPrice: 899.99,
    category: "electronics",
    stock: 20,
    images: ["samsung_qled_1.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Logitech MX Master 3S Mouse",
    description:
      "Advanced wireless mouse with ultra-fast MagSpeed scrolling, 8K DPI sensor, ergonomic design, and silent clicks.",
    price: 99.99,
    discountPrice: 79.99,
    category: "electronics",
    stock: 150,
    images: ["mx_master_3s.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Anker 65W USB-C Charger",
    description:
      "Compact 65W GaN charger with PowerIQ 3.0. Charge a MacBook Pro, iPad, and iPhone simultaneously with 3 ports.",
    price: 45.99,
    category: "electronics",
    stock: 300,
    images: ["anker_65w.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Bose QuietComfort 45 Headphones",
    description:
      "Noise cancelling wireless headphones with world-class Bose noise cancellation, 24-hour battery and comfortable over-ear design.",
    price: 329.99,
    discountPrice: 249.99,
    category: "electronics",
    stock: 70,
    images: ["bose_qc45.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Kindle Paperwhite (16GB)",
    description:
      "Now with a 6.8-inch display and thinner borders, adjustable warm light, up to 10 weeks of battery life, and waterproof design.",
    price: 139.99,
    discountPrice: 114.99,
    category: "electronics",
    stock: 200,
    images: ["kindle_paperwhite.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "GoPro HERO12 Black",
    description:
      "Shoot 5.3K60 video, 27MP photos. HyperSmooth 6.0 stabilization, Enduro battery, and waterproof to 33ft without a case.",
    price: 399.99,
    discountPrice: 349.99,
    category: "electronics",
    stock: 45,
    images: ["gopro_hero12.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Razer DeathAdder V3 Gaming Mouse",
    description:
      "Ultra-lightweight esports mouse with Focus Pro 30K optical sensor, 90-hour battery life and optical mouse switches.",
    price: 89.99,
    category: "electronics",
    stock: 120,
    images: ["razer_deathadder_v3.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Apple AirPods Pro (2nd Gen)",
    description:
      "Active Noise Cancellation, Transparency mode, Adaptive Audio, and Personalized Spatial Audio with MagSafe USB-C charging case.",
    price: 249.99,
    discountPrice: 189.99,
    category: "electronics",
    stock: 175,
    images: ["airpods_pro_2.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "WD 2TB External Hard Drive",
    description:
      "Plug-and-play USB 3.0 portable drive for PC, Mac, PlayStation and Xbox. 2TB capacity in a slim, compact design.",
    price: 69.99,
    discountPrice: 54.99,
    category: "electronics",
    stock: 250,
    images: ["wd_2tb.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "TP-Link WiFi 6 Router (AX3000)",
    description:
      "Next-gen WiFi 6 with 3 Gbps speed, 4 high-gain antennas, OFDMA, MU-MIMO technology for ultra-fast and reliable connections.",
    price: 129.99,
    discountPrice: 99.99,
    category: "electronics",
    stock: 90,
    images: ["tplink_ax3000.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Mechanical Keyboard (TKL, Brown Switches)",
    description:
      "Tenkeyless mechanical keyboard with Gateron Brown switches, PBT double-shot keycaps, per-key RGB and USB-C detachable cable.",
    price: 79.99,
    category: "electronics",
    stock: 110,
    images: ["mech_keyboard_tkl.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Ring Video Doorbell Pro 2",
    description:
      "Head-to-Toe HD+ Video, 3D Motion Detection with Bird's Eye View, dual-band WiFi, and two-way talk with noise cancellation.",
    price: 249.99,
    discountPrice: 179.99,
    category: "electronics",
    stock: 65,
    images: ["ring_doorbell_pro2.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Sony ZV-E10 Mirrorless Camera",
    description:
      "APS-C sensor mirrorless camera with 4K video, fast hybrid autofocus, detachable kit lens and real-time eye autofocus for creators.",
    price: 748.00,
    discountPrice: 648.00,
    category: "electronics",
    stock: 35,
    images: ["sony_zve10.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },

  // ─── CLOTHING (12) ───────────────────────────────────────
  {
    name: "Levi's 511 Slim Fit Jeans",
    description:
      "Classic slim-fit jeans crafted from stretch denim for all-day comfort. Sits below the waist, slim through the thigh and leg.",
    price: 59.99,
    discountPrice: 44.99,
    category: "clothing",
    stock: 400,
    images: ["levis_511.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Nike Dri-FIT Running T-Shirt",
    description:
      "Sweat-wicking Dri-FIT fabric keeps you dry and comfortable. Lightweight, breathable mesh panels for ventilation during intense runs.",
    price: 34.99,
    discountPrice: 24.99,
    category: "clothing",
    stock: 500,
    images: ["nike_dri_fit.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Adidas Ultraboost 22 Running Shoes",
    description:
      "Responsive BOOST midsole, Primeknit upper for a snug fit, and Continental rubber outsole for superior grip in all conditions.",
    price: 189.99,
    discountPrice: 139.99,
    category: "clothing",
    stock: 90,
    images: ["adidas_ultraboost22.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "The North Face Thermoball Eco Jacket",
    description:
      "Packable insulated jacket made with 100% recycled materials. ThermoBall Eco insulation keeps you warm even when wet.",
    price: 199.99,
    discountPrice: 149.99,
    category: "clothing",
    stock: 75,
    images: ["tnf_thermoball.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Uniqlo Ultra Light Down Jacket",
    description:
      "Feather-light puffer jacket that packs into its own pocket. Down fill offers maximum warmth at minimal weight.",
    price: 79.99,
    discountPrice: 59.99,
    category: "clothing",
    stock: 200,
    images: ["uniqlo_down.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Champion Reverse Weave Hoodie",
    description:
      "Iconic heavyweight hoodie with ribbed cuffs, kangaroo pocket, and embroidered logo. A streetwear staple since 1919.",
    price: 65.00,
    category: "clothing",
    stock: 300,
    images: ["champion_hoodie.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Columbia Pfg Tamiami Fishing Shirt",
    description:
      "UPF 40 sun protection, Omni-Wick sweat management, vented back, rod holder and utility pocket for fishing trips.",
    price: 55.00,
    category: "clothing",
    stock: 180,
    images: ["columbia_pfg.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Hanes Men's 6-Pack ComfortSoft T-Shirts",
    description:
      "Tagless crew-neck tees in soft ComfortSoft cotton. Pre-shrunk to maintain size and shape wash after wash.",
    price: 29.99,
    discountPrice: 22.99,
    category: "clothing",
    stock: 600,
    images: ["hanes_6pack.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Patagonia Better Sweater Fleece Jacket",
    description:
      "Classic fleece made from 100% recycled polyester with a sweater-knit face. Zip-up collar and zippered pockets.",
    price: 139.00,
    discountPrice: 109.00,
    category: "clothing",
    stock: 130,
    images: ["patagonia_sweater.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Birkenstock Arizona Sandals",
    description:
      "Two-strap sandal with contoured cork-latex footbed, suede lining and adjustable buckles for a custom fit.",
    price: 109.95,
    discountPrice: 84.95,
    category: "clothing",
    stock: 160,
    images: ["birkenstock_arizona.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Smartwool Merino 150 Base Layer Top",
    description:
      "Ultrafine 17.5-micron Merino wool base layer that regulates temperature, resists odour and is machine washable.",
    price: 99.95,
    discountPrice: 74.95,
    category: "clothing",
    stock: 95,
    images: ["smartwool_150.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Lululemon Align High-Rise Leggings",
    description:
      "Buttery-soft Nulu fabric with a weightless, naked sensation. High-rise waistband and four-way stretch for yoga and beyond.",
    price: 128.00,
    discountPrice: 98.00,
    category: "clothing",
    stock: 220,
    images: ["lululemon_align.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },

  // ─── BOOKS (10) ──────────────────────────────────────────
  {
    name: "Atomic Habits by James Clear",
    description:
      "A proven framework for improving every day. Learn how tiny changes in behaviour can lead to remarkable results.",
    price: 19.99,
    discountPrice: 14.99,
    category: "books",
    stock: 500,
    images: ["atomic_habits.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "The Pragmatic Programmer (20th Anniversary Edition)",
    description:
      "Timeless advice on software craftsmanship, career development, and delivering great code from David Thomas and Andrew Hunt.",
    price: 49.99,
    discountPrice: 39.99,
    category: "books",
    stock: 200,
    images: ["pragmatic_programmer.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Clean Code by Robert C. Martin",
    description:
      "A handbook of agile software craftsmanship. Covers how to write, read and refactor code to be clean and maintainable.",
    price: 44.99,
    discountPrice: 34.99,
    category: "books",
    stock: 175,
    images: ["clean_code.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "You Don't Know JS (6-Book Set)",
    description:
      "Kyle Simpson's deep dive series into JavaScript mechanics including scope, closures, async, ES6 and beyond.",
    price: 89.99,
    discountPrice: 69.99,
    category: "books",
    stock: 120,
    images: ["ydkjs.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Designing Data-Intensive Applications",
    description:
      "Martin Kleppmann explains the principles behind reliable, scalable and maintainable distributed systems and databases.",
    price: 59.99,
    discountPrice: 49.99,
    category: "books",
    stock: 150,
    images: ["ddia.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "The Lean Startup by Eric Ries",
    description:
      "How constant innovation creates radically successful businesses. Validated learning, rapid experimentation and iterative product releases.",
    price: 18.99,
    category: "books",
    stock: 300,
    images: ["lean_startup.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "JavaScript: The Good Parts",
    description:
      "Douglas Crockford uncovers the features of JavaScript that make it a powerful and expressive language while exposing the bad parts.",
    price: 29.99,
    discountPrice: 21.99,
    category: "books",
    stock: 210,
    images: ["js_good_parts.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "System Design Interview Vol. 1 & 2",
    description:
      "Alex Xu's comprehensive guide to cracking system design interviews at top tech companies. Covers scalable architecture patterns.",
    price: 69.99,
    discountPrice: 54.99,
    category: "books",
    stock: 180,
    images: ["system_design_interview.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Deep Work by Cal Newport",
    description:
      "Rules for focused success in a distracted world. How to cultivate the ability to focus without distraction on demanding tasks.",
    price: 17.99,
    discountPrice: 12.99,
    category: "books",
    stock: 400,
    images: ["deep_work.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "The Psychology of Money by Morgan Housel",
    description:
      "Timeless lessons on wealth, greed, and happiness. 19 short stories exploring the strange ways people think about money.",
    price: 18.99,
    discountPrice: 13.99,
    category: "books",
    stock: 450,
    images: ["psychology_of_money.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },

  // ─── FOOD (7) ────────────────────────────────────────────
  {
    name: "Lavazza Super Crema Espresso Beans (2.2lb)",
    description:
      "Velvety and rich blend of Arabica and Robusta beans. Medium espresso roast with notes of hazelnut, brown sugar and dried fruit.",
    price: 22.99,
    discountPrice: 18.99,
    category: "food",
    stock: 350,
    images: ["lavazza_super_crema.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "KIND Snack Bars Variety Pack (30 Count)",
    description:
      "30 gluten-free bars across 6 flavours. Made with real whole nuts, 5g of sugar or less, and non-GMO ingredients.",
    price: 29.99,
    discountPrice: 24.99,
    category: "food",
    stock: 600,
    images: ["kind_bars.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Himalayan Pink Salt (5lb Bag)",
    description:
      "Unrefined, unprocessed raw Himalayan pink salt. Rich in minerals, no additives. Perfect for cooking, baking and seasoning.",
    price: 14.99,
    discountPrice: 10.99,
    category: "food",
    stock: 400,
    images: ["himalayan_salt.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Organic Peanut Butter (16oz, 2-Pack)",
    description:
      "100% organic dry-roasted peanuts, no added sugar or palm oil. Creamy texture, rich flavour, non-GMO certified.",
    price: 16.99,
    category: "food",
    stock: 500,
    images: ["organic_pb.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Ghirardelli Premium Dark Chocolate Assortment",
    description:
      "60-piece premium assortment of Midnight Reverie, Intense Dark and Twilight Delight squares in a keepsake gift box.",
    price: 34.99,
    discountPrice: 27.99,
    category: "food",
    stock: 250,
    images: ["ghirardelli_dark.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "McCormick Grill Mates Spice Set (8 Pack)",
    description:
      "Curated set of 8 bold seasonings: Montreal Steak, Applewood Rub, Brazilian Steakhouse, Baja Citrus and more.",
    price: 24.99,
    discountPrice: 19.99,
    category: "food",
    stock: 300,
    images: ["mccormick_grillmates.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Optimum Nutrition Gold Standard Whey Protein (5lb)",
    description:
      "24g of whey protein per serving, 5.5g of naturally occurring BCAAs. Low in fat and sugar, 74 servings per container.",
    price: 79.99,
    discountPrice: 64.99,
    category: "food",
    stock: 180,
    images: ["on_gold_whey.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },

  // ─── FURNITURE (6) ───────────────────────────────────────
  {
    name: "IKEA BEKANT Sit/Stand Desk (63x31 in)",
    description:
      "Electric height-adjustable desk with whisper-quiet motor, memory function for 3 programmable heights and 10-year warranty.",
    price: 489.99,
    discountPrice: 429.99,
    category: "furniture",
    stock: 30,
    images: ["ikea_bekant.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Secretlab TITAN Evo 2022 Gaming Chair",
    description:
      "Full-length lumbar support system, leatherette upholstery with 4-way L-ADAPT lumbar support and multi-tilt recline.",
    price: 519.00,
    discountPrice: 459.00,
    category: "furniture",
    stock: 25,
    images: ["secretlab_titan.jpg"],
    seller: pick(sellers),
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Autonomous SmartDesk Pro",
    description:
      "Dual-motor standing desk with 265lb lifting capacity, 51-inch height range, robust steel frame and cable management tray.",
    price: 599.00,
    discountPrice: 499.00,
    category: "furniture",
    stock: 20,
    images: ["autonomous_smartdesk.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Furinno Turn-S-Tube 5-Tier Bookcase",
    description:
      "Easy-to-assemble 5-tier corner bookshelf in Espresso/Black. Made from engineered wood with no tools required.",
    price: 44.99,
    discountPrice: 34.99,
    category: "furniture",
    stock: 80,
    images: ["furinno_bookcase.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Flash Furniture Mid-Back Ergonomic Office Chair",
    description:
      "Mesh back, padded seat, adjustable armrests, lumbar support and pneumatic seat height adjustment for all-day comfort.",
    price: 189.99,
    discountPrice: 149.99,
    category: "furniture",
    stock: 55,
    images: ["flash_office_chair.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Nathan James Amara 6-Drawer Dresser",
    description:
      "Modern dresser with solid wood legs, soft-close drawers, metal glides and a white/light oak two-tone finish.",
    price: 279.99,
    discountPrice: 229.99,
    category: "furniture",
    stock: 35,
    images: ["nathan_james_dresser.jpg"],
    seller: pick(sellers),
    isFeatured: false,
    isActive: true,
  },
];

module.exports = products;
